version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - composer install --no-interaction
      - npm ci
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cp .env.example .env.testing
      - php artisan key:generate --env=testing
      - ./vendor/bin/phpunit --configuration=phpunit.xml --testdox
  build:
    commands:
      - echo Entered the build phase...
      - npm run production
  post_build:
    commands:
      - echo Entered the post_build phase...
artifacts:
  files:
    - .ebextensions/**/*
    - app/**/*
    - artisan
    - bootstrap/**/*
    - composer.json
    - composer.lock
    - config/**/*
    - database/**/*
    - package-lock.json
    - package.json
    - public/**/*
    - resources/**/*
    - routes/*
    - storage/**/*
    - webpack.mix.js
