<?php

namespace App\Jobs;

use App\Hostname;
use Aws\Route53\Route53Client;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use Throwable;

class DeleteRecordSet implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * @var Hostname
     */
    private $hostname;

    public function __construct(Hostname $hostname)
    {
        $this->hostname = $hostname;
    }

    public function handle(Route53Client $route53Client): void
    {
        try {
            $route53Client->changeResourceRecordSets([
                'HostedZoneId' => config('itup.hosted_zone_id'),
                'ChangeBatch' => [
                    'Comment' => 'Generated by ' . config('app.name'),
                    'Changes' => [
                        [
                            'Action' => 'DELETE',
                            'ResourceRecordSet' => [
                                'Name' => $this->hostname->fullName() . '.',
                                'TTL' => 300,
                                'Type' => 'A',
                                'ResourceRecords' => [
                                    [
                                        'Value' => $this->hostname->ip
                                    ],
                                ],
                            ]
                        ],
                    ],
                ]
            ]);

            $this->hostname->delete();
        } catch (Throwable $e) {
            Log::error('Could not delete recordset' . $this->hostname->name, [
                'hostname' => $this->hostname,
                'exception' => $e,
            ]);
        }
    }
}
